# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-release
sudo: false
cache: packages
warnings_are_errors: false
r_build_args: "--no-build-vignettes"
r_check_args: "--as-cran --no-build-vignettes"
after_success:
  - Rscript -e 'covr::codecov()'

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
